const data = [
  {
    id: 1,
    cattegory_name: "Men",
    google_cattegory: "men",
    brand: "Ttrimmer",
    purchase_price: null,
    code: "VB-001",
    title: "Electric Hair Clippers Profess",
    status: "2",
    price_list: "6.5 : 1, 12 : 2, 18 : 2, 23 : 4, 27 : 5",
    price: 6.5,
    old_price: 8,
    offer_percentage: 19,
    with_vat: 7,
    view_vat: 2,
    description: "Product Details Electric Hair Clippers Professional T Blade",
    color: "Black",
    size: 0,
    delivery_charges: 0,
    quantity: 50,
    quantity_text: "",
    fake_order_sold: 22,
    rank: 1,
    image: "/images/products/product1.png",
    created_at: "2022-02-23T04:43:53.000Z",
    updated_at: "2022-02-23T04:43:53.000Z",
    available_in: "1,2",
  },
  {
    id: 2,
    cattegory_name: "Kitchenware",
    google_cattegory: "",
    brand: "Universal",
    purchase_price: null,
    code: "AS1",
    title: "2 pcs F2 Screen Enlarger",
    status: 1,
    price_list: "4 : 1 piece, 10: 3 pieces, 15: 5 pieces",
    price: 4,
    old_price: 8,
    offer_percentage: 50,
    with_vat: 4,
    view_vat: 2,
    description: "HD Black F2 Mobile Phone Screen Amplifier Thicken Lens Mobil",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 100,
    quantity_text: "",
    fake_order_sold: 0,
    rank: 9,
    image: "/images/products/product2.jpeg",
    created_at: "2022-02-23T04:51:03.000Z",
    updated_at: "2022-02-23T04:51:03.000Z",
  },
  {
    id: 3,
    cattegory_name: "Gadgets",
    google_cattegory: "",
    brand: "Universal",
    purchase_price: null,
    code: "AS2",
    title: "2in1 Bluetooth and Powerbank",
    status: 1,
    price_list: "",
    price: 6.6,
    old_price: 12,
    offer_percentage: 45,
    with_vat: 7,
    view_vat: 2,
    description: "2in1 Touch Sensor 5.0 Bluetooth Earpods and 1200mAH Emergenc",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 100,
    quantity_text: "",
    fake_order_sold: 0,
    rank: 34,
    image: "/images/products/product3.jpeg",
    created_at: "2022-02-23T04:54:00.000Z",
    updated_at: "2022-02-23T04:54:00.000Z",
  },
  {
    id: 4,
    cattegory_name: "Women",
    google_cattegory: null,
    brand: "Universal",
    purchase_price: null,
    code: "AS3",
    title: "3 Fold Back View Mirror",
    status: 1,
    price_list: null,
    price: 9,
    old_price: 16,
    offer_percentage: 44,
    with_vat: 9,
    view_vat: 2,
    description: "Elegant 3 Fold Back View Mirror with hanging Option",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 100,
    quantity_text: null,
    fake_order_sold: null,
    rank: 34,
    image: "/images/products/product4.jpeg",
    created_at: "2022-02-23T04:59:35.000Z",
    updated_at: "2022-02-23T04:59:35.000Z",
  },
  {
    id: 6,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "Probuds/mobile stand",
    purchase_price: null,
    code: "124",
    title: "Probuds 0.5/Mobile stand",
    status: 1,
    price_list: "7.5: One deal, 15: two deals",
    price: 7.5,
    old_price: 12,
    offer_percentage: 37,
    with_vat: 8,
    view_vat: 2,
    description: "Probuds / mobile stand",
    color: "white",
    size: 0,
    delivery_charges: 0,
    quantity: 15,
    quantity_text: "15",
    fake_order_sold: null,
    rank: 25,
    image: "/images/products/product5.jpeg",
    created_at: "2022-02-23T05:08:45.000Z",
    updated_at: "2022-02-23T05:08:45.000Z",
  },
  {
    id: 8,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "scarlet kettle and juicer",
    purchase_price: "5",
    code: "557",
    title: "2in1 offer",
    status: 1,
    price_list: "6.9",
    price: 6.9,
    old_price: 13,
    offer_percentage: 47,
    with_vat: 7,
    view_vat: 2,
    description: "2in bundle offer, 2L electric kettle and rechargeable blende",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 20,
    quantity_text: null,
    fake_order_sold: null,
    rank: 11,
    image: "/images/products/product5.jpeg",
    created_at: "2022-02-23T05:13:24.000Z",
    updated_at: "2022-02-23T05:13:24.000Z",
  },
  {
    id: 9,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "scarlet kettle and juicer",
    purchase_price: "5",
    code: "557",
    title: "2in1 offer",
    status: 1,
    price_list: "6.9",
    price: 6.9,
    old_price: 13,
    offer_percentage: 47,
    with_vat: 7,
    view_vat: 2,
    description: "2in bundle offer, 2L electric kettle and rechargeable blende",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 20,
    quantity_text: null,
    fake_order_sold: null,
    rank: 11,
    image: "/images/products/product6.jpeg",
    created_at: "2022-02-23T05:13:51.000Z",
    updated_at: "2022-02-23T05:13:51.000Z",
  },
  {
    id: 10,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "scarlet kettle and juicer",
    purchase_price: "5",
    code: "557",
    title: "2in1 offer",
    status: 1,
    price_list: "6.9",
    price: 6.9,
    old_price: 13,
    offer_percentage: 47,
    with_vat: 7,
    view_vat: 2,
    description: "2in bundle offer, 2L electric kettle and rechargeable blende",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 20,
    quantity_text: null,
    fake_order_sold: null,
    rank: 11,
    image: "/images/products/product7.jpeg",
    created_at: "2022-02-23T05:14:17.000Z",
    updated_at: "2022-02-23T05:14:17.000Z",
  },
  {
    id: 11,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "scarlet kettle and juicer",
    purchase_price: "5",
    code: "557",
    title: "2in1 offer",
    status: 1,
    price_list: "6.9",
    price: 6.9,
    old_price: 13,
    offer_percentage: 47,
    with_vat: 7,
    view_vat: 2,
    description: "2in bundle offer, 2L electric kettle and rechargeable blende",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 20,
    quantity_text: null,
    fake_order_sold: null,
    rank: 11,
    image: "/images/products/product8.jpeg",
    created_at: "2022-02-23T05:14:51.000Z",
    updated_at: "2022-02-23T05:14:51.000Z",
  },
  {
    id: 12,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "scarlet kettle and juicer",
    purchase_price: "5",
    code: "557",
    title: "2in1 offer",
    status: 1,
    price_list: "6.9",
    price: 6.9,
    old_price: 13,
    offer_percentage: 47,
    with_vat: 7,
    view_vat: 2,
    description: "2in bundle offer, 2L electric kettle and rechargeable blende",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 20,
    quantity_text: null,
    fake_order_sold: null,
    rank: 11,
    image: "/images/products/product9.jpeg",
    created_at: "2022-02-23T05:15:11.000Z",
    updated_at: "2022-02-23T05:15:11.000Z",
  },
  {
    id: 13,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "scarlet kettle and juicer",
    purchase_price: "5",
    code: "557",
    title: "2in1 offer",
    status: 1,
    price_list: "6.9",
    price: 6.9,
    old_price: 13,
    offer_percentage: 47,
    with_vat: 7,
    view_vat: 2,
    description: "2in bundle offer, 2L electric kettle and rechargeable blende",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 20,
    quantity_text: null,
    fake_order_sold: null,
    rank: 11,
    image: "/images/products/product10.jpeg",
    created_at: "2022-02-23T05:15:31.000Z",
    updated_at: "2022-02-23T05:15:31.000Z",
  },
  {
    id: 14,
    cattegory_name: "*Hot Deals*",
    google_cattegory: null,
    brand: "scarlet kettle and juicer",
    purchase_price: "5",
    code: "557",
    title: "2in1 offer",
    status: 1,
    price_list: "6.9",
    price: 6.9,
    old_price: 13,
    offer_percentage: 47,
    with_vat: 7,
    view_vat: 2,
    description: "2in bundle offer, 2L electric kettle and rechargeable blende",
    color: "",
    size: 0,
    delivery_charges: 0,
    quantity: 20,
    quantity_text: null,
    fake_order_sold: null,
    rank: 11,
    image: "/images/products/product11.jpeg",
    created_at: "2022-02-23T05:15:55.000Z",
    updated_at: "2022-02-23T05:15:55.000Z",
  },
];

export default data;
