export const data = [
  {
    id: 1,
    name: "laptop",
    description: "Laptop accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/laptop.png",
    discount: 44,
  },
  {
    id: 2,
    name: "watch",
    description: "Kichen Appliances for home use",
    price: 12,
    oldPrice: 15,
    image: "/pr1.png",
    discount: 45,
  },
  {
    id: 3,
    name: "spoon",
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr2.png",
    discount: 46,
  },
  {
    id: 4,
    name: "watch",
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr3.png",
    discount: 50,
  },
  {
    id: 5,
    name: "makeup",
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/makeup.png",
    discount: 30,
  },
  {
    id: 6,
    name: "laptop",
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/laptop.png",
    discount: 33,
  },
  {
    id: 7,
    name: "watch",
    description: "Kitchen Appliances for home use",
    price: 12,
    oldPrice: 15,
    image: "/pr1.png",
    discount: 34,
  },
  {
    id: 8,
    name: "kitchen",
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr2.png",
    discount: 35,
  },
  {
    id: 9,
    name: "laptop",
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr3.png",
    discount: 36,
  },
  {
    id: 10,
    name: "makeup",
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/makeup.png",
    discount: 40,
  },
];
