export const data = [
  {
    id: 1,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/laptop.png",
    discount: 44,
  },
  {
    id: 2,
    description: "Kichen Appliances for home use",
    price: 12,
    oldPrice: 15,
    image: "/pr1.png",
    discount: 44,
  },
  {
    id: 3,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr2.png",
    discount: 44,
  },
  {
    id: 4,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr3.png",
    discount: 44,
  },
  {
    id: 5,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/makeup.png",
    discount: 44,
  },
  {
    id: 6,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/laptop.png",
    discount: 44,
  },
  {
    id: 7,
    description: "Kitchen Appliances for home use",
    price: 12,
    oldPrice: 15,
    image: "/pr1.png",
    discount: 44,
  },
  {
    id: 8,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr2.png",
    discount: 44,
  },
  {
    id: 9,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/pr3.png",
    discount: 44,
  },
  {
    id: 10,
    description: "Computer accessories for office use",
    price: 12,
    oldPrice: 15,
    image: "/makeup.png",
    discount: 44,
  },
];
