const data = [
  {
    order_id: 7,
    client_id: 20,
    product_id: 1,
    quantity: 50,
    amount: 81,
    delivery_charges: 0,
    quantity_text: "",
    color: "#1BE600",
    status: "NEW",
    delivery_note: "",
    created_at: "2022-02-25T04:41:28.000Z",
    updated_at: "2022-02-25T04:42:00.000Z",
    id: 1,
    full_name: "Tufail",
    phone: "921234567698689",
    address: "Molestiae labore eiu",
    country: "",
    city: "Abu Dhabi Municipality",
    cattegory_name: "Men",
    google_cattegory: "men",
    brand: "Ttrimmer",
    purchase_price: null,
    code: "VB-001",
    title: "Electric Hair Clippers Profess",
    price_list: "6.5 : 1, 12 : 2, 18 : 2, 23 : 4, 27 : 5",
    price: 6.5,
    old_price: 8,
    offer_percentage: 19,
    with_vat: 7,
    view_vat: 2,
    description: "When order is created",
    size: 0,
    fake_order_sold: 22,
    rank: 1,
    image: "/images/products/product1.png",
  },
  {
    order_id: 8,
    client_id: 21,
    product_id: 1,
    quantity: 50,
    amount: 5.6,
    delivery_charges: 0,
    quantity_text: "",
    color: "#1BE600",
    status: "NEW",
    delivery_note: "",
    created_at: "2022-02-25T04:41:28.000Z",
    updated_at: "2022-02-25T04:42:00.000Z",
    id: 1,
    full_name: "Uzair Nasir",
    phone: "9212345678",
    address: "sjhanvdwejvdcej xcjas uxegugsa",
    country: "",
    city: "Dibba Al-Hisn",
    cattegory_name: "Men",
    google_cattegory: "men",
    brand: "Ttrimmer",
    purchase_price: null,
    code: "VB-001",
    title: "Electric Hair Clippers Profess",
    price_list: "6.5 : 1, 12 : 2, 18 : 2, 23 : 4, 27 : 5",
    price: 6.5,
    old_price: 8,
    offer_percentage: 19,
    with_vat: 7,
    view_vat: 2,
    description: "When order is created",
    size: 0,
    fake_order_sold: 22,
    rank: 1,
    image: "/images/products/product1.png",
  },
  {
    order_id: 9,
    client_id: 21,
    product_id: 1,
    quantity: 50,
    amount: 81,
    delivery_charges: 0,
    quantity_text: "",
    color: "#1BE600",
    status: "NEW",
    delivery_note: "",
    created_at: "2022-02-25T04:41:28.000Z",
    updated_at: "2022-02-25T04:42:00.000Z",
    id: 1,
    full_name: "Uzair Nasir",
    phone: "9212345678",
    address: "sjhanvdwejvdcej xcjas uxegugsa",
    country: "",
    city: "Dibba Al-Hisn",
    cattegory_name: "Men",
    google_cattegory: "men",
    brand: "Ttrimmer",
    purchase_price: null,
    code: "VB-001",
    title: "Electric Hair Clippers Profess",
    price_list: "6.5 : 1, 12 : 2, 18 : 2, 23 : 4, 27 : 5",
    price: 6.5,
    old_price: 8,
    offer_percentage: 19,
    with_vat: 7,
    view_vat: 2,
    description: "When order is created",
    size: 0,
    fake_order_sold: 22,
    rank: 1,
    image: "/images/products/product1.png",
  },
  {
    order_id: 11,
    client_id: 22,
    product_id: 1,
    quantity: 50,
    amount: 21,
    delivery_charges: 0,
    quantity_text: "",
    color: "#1BE600",
    status: "NEW",
    delivery_note: "",
    created_at: "2022-02-25T04:41:28.000Z",
    updated_at: "2022-02-25T04:42:00.000Z",
    id: 1,
    full_name: "Muhib ullah",
    phone: "92123456789",
    address: "bwsiadbweikxbiebxiko",
    country: "",
    city: "Adh Dhayd",
    cattegory_name: "Men",
    google_cattegory: "men",
    brand: "Ttrimmer",
    purchase_price: null,
    code: "VB-001",
    title: "Electric Hair Clippers Profess",
    price_list: "6.5 : 1, 12 : 2, 18 : 2, 23 : 4, 27 : 5",
    price: 6.5,
    old_price: 8,
    offer_percentage: 19,
    with_vat: 7,
    view_vat: 2,
    description: "When order is created",
    size: 0,
    fake_order_sold: 22,
    rank: 1,
    image: "/images/products/product1.png",
  },
  {
    order_id: 12,
    client_id: 21,
    product_id: 2,
    quantity: 100,
    amount: 4,
    delivery_charges: 0,
    quantity_text: "",
    color: "#1BE600",
    status: "NEW",
    delivery_note: "",
    created_at: "2022-02-25T04:41:28.000Z",
    updated_at: "2022-02-25T04:42:00.000Z",
    id: 1,
    full_name: "Uzair Nasir",
    phone: "9212345678",
    address: "sjhanvdwejvdcej xcjas uxegugsa",
    country: "",
    city: "Dibba Al-Hisn",
    cattegory_name: "Kitchenware",
    google_cattegory: "",
    brand: "Universal",
    purchase_price: null,
    code: "AS1",
    title: "2 pcs F2 Screen Enlarger",
    price_list: "4 : 1 piece, 10: 3 pieces, 15: 5 pieces",
    price: 4,
    old_price: 8,
    offer_percentage: 50,
    with_vat: 4,
    view_vat: 2,
    description: "When order is created",
    size: 0,
    fake_order_sold: 0,
    rank: 9,
    image: "/images/products/product2.jpeg",
  },
  {
    order_id: 13,
    client_id: 23,
    product_id: 2,
    quantity: 100,
    amount: 1,
    delivery_charges: 0,
    quantity_text: "",
    color: "#1BE600",
    status: "NEW",
    delivery_note: "",
    created_at: "2022-02-25T04:41:28.000Z",
    updated_at: "2022-02-25T04:42:00.000Z",
    id: 1,
    full_name: "Mansor",
    phone: "997238963876",
    address: "uwsgui32gsdug2ud1gu2gdo",
    country: "",
    city: "Dibba Al Fujairah Municipality",
    cattegory_name: "Kitchenware",
    google_cattegory: "",
    brand: "Universal",
    purchase_price: null,
    code: "AS1",
    title: "2 pcs F2 Screen Enlarger",
    price_list: "4 : 1 piece, 10: 3 pieces, 15: 5 pieces",
    price: 4,
    old_price: 8,
    offer_percentage: 50,
    with_vat: 4,
    view_vat: 2,
    description: "When order is created",
    size: 0,
    fake_order_sold: 0,
    rank: 9,
    image: "/images/products/product2.jpeg",
  },
];

export default data;
